version: '3.9'

services:
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@exapmle.com}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pgadmin}
        ports:
            - "5050:80"
        restart: unless-stopped
        volumes:
            - pga_data:/var/lib/pgadmin

volumes:
    pga_data: